version: '3'

services:
  mongo-service:
    restart: always
    image: mongo
    container_name: refugee-mongodb
    volumes:
      - ./RefugeeMongoDB/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./RefugeeMongoDB/data-import.sh:/docker-entrypoint-initdb.d/data-import.sh:ro
      - ./RefugeeMongoDB/mongo-volume:/data/db
    ports:
      - '27017-27019:27017-27019'
  
  #camunda-service:
  #  restart: always
  #  image: camunda/camunda-bpm-platform:run-latest
  #  container_name: camunda-run
  #  ports: 
  #    - '8080:8080'
    
  #siddhi-service:
  #  restart: always
  #  image: siddhiio/siddhi-tooling
  #  container_name: siddhi-tooling
  #  ports:
  #    - '9390:9390' 
  #    - '8006:8006'
  #  volumes:
  #    - ./Siddhi/jars:/siddhi-tooling/jars
