version: '3'

services:
  siddhi-application:
    build: ./siddhi-files/siddhi-event-apps
    restart: always
    container_name: siddhi-refugee-apps
    ports:
      - 9090:9090
      - 9443:9443
      - 8004:8004
      - 8005:8005
      - 8006:8006

  python-scripts:
    build: ./python-scripts
    restart: always
    container_name: python-scripts
    depends_on:
      - "siddhi-application"
    ports:
      - "4999:4999"
    network_mode: "host"

  transportation-api:
    build: ./process-transportation/transportation-api
    restart: always
    ports:
      - "80:80"
    container_name: transportation-api
    network_mode: "host"
  
  job-script:
    build: ./process-job
    restart: always
    container_name: job-script
    network_mode: "host"
    depends_on:
      - "siddhi-application"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8004"]
        interval: 30s
        timeout: 10s
        retries: 10


  
  #camunda-service:
  #  restart: always
  #  image: camunda/camunda-bpm-platform:run-latest
  #  container_name: camunda-run
  #  ports: 
  #    - '8080:8080'

  #mongo-service:
  #  restart: always
  #  image: mongo
  #  container_name: refugee-mongodb
  #  volumes:
  #    - ./refugee-mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
  #    - ./refugee-mongodb/data-import.sh:/docker-entrypoint-initdb.d/data-import.sh:ro
  #    - ./refugee-mongodb/mongo-volume:/data/db
  #  ports:
  #    - '27017-27019:27017-27019'
    
  #siddhi-service:
  #  restart: always
  #  image: siddhiio/siddhi-tooling
  #  container_name: siddhi-tooling
  #  ports:
  #    - '9390:9390' 
  #    - '8006:8006'
  #  volumes:
  #    - ./Siddhi/jars:/siddhi-tooling/jars
